### ISSUE TITLE
Would it be possible to modify this to work with a mesh using blend shapes?

### ISSUE THREAD

**Issue by eranhaas** [keijiro/Skinner#1]

**Comment by keijiro** [comment]
Yes, it could. Before considering it, I should finish implementation though (it's still in a very early stage).

Just out of curious, what kind of blending animation are you thinking of? I rarely use blend shapes and thus have no idea about its usage.

**Comment by eranhaas** [comment]
Thanks

I have been using blend shapes to give some organic sort of movement to abstract geometry. It is a lot of fun with sound driven stuff.

Example here, starting around 2:40.
https://vimeo.com/194133499

Here is the mesh I was using.
https://dl.dropboxusercontent.com/u/81726460/Blendshape.unitypackage

**Comment by keijiro** [comment]
This project has been already outdated, so there won't be new features. This should be revisited in Smrvfx: https://github.com/keijiro/Smrvfx
