### ISSUE TITLE
Can't convert 

### ISSUE THREAD

**Issue by iwanPlays** [keijiro/Skinner#13]
I'm trying to test Skinner with Robot Lab https://www.assetstore.unity3d.com/en/#!/content/7006 but can't convert meshes:
```
The given mesh (prop_floorBot_female) is not skinned. Skinner only can handle skinned meshes.
UnityEngine.Debug:LogError(Object)
Skinner.SkinnerModelEditor:CheckSkinned(Mesh) (at Assets/Skinner/Editor/SkinnerModelEditor.cs:34)
Skinner.SkinnerModelEditor:ConvertAssets() (at Assets/Skinner/Editor/SkinnerModelEditor.cs:54)
```

What is a skinned mesh?

PS: it works with for example the robot legs in https://www.assetstore.unity3d.com/en/#!/content/75207 - In case somebody else is just trying to just see the results for themselves first. :)

**Comment by keijiro** [comment]
Skinner is a specialized renderer that is developed as a tricky workaround for limitations of skinned meshes. So, if you're using a rigid mesh (not skinned one), you don't have to use Skinner at all.

**Comment by keijiro** [comment]
I'm closing this issue because it's out of the scope of this repository. I'd recommend reading documents/tutorials about game character creation and skeletal animation.

https://en.wikipedia.org/wiki/Skeletal_animation

If you meet the same issue even when using a properly skinned mesh, please feel free to reopen the issue.

**Comment by iwanPlays** [comment]
Absolutely.

I'm not sure "skinned mesh" is a clear term though. Perhaps you could clarify (mesh that has to have at least one bone?)

Anyways, this link might help in case somebody ends up with the same problem: https://docs.unity3d.com/Manual/class-SkinnedMeshRenderer.html

**Comment by keijiro** [comment]
skinned mesh == mesh with vertex weights
