### ISSUE TITLE
Skinner Not working with Unity 5.6 and VR.

### ISSUE THREAD

**Issue by ddutchie** [keijiro/Skinner#14]
Running the Repo project and enabling VR breaks Skinner. Nothing Renders? 

I'm sure it has worked before?

**Comment by keijiro** [comment]
I'm pretty sure it should work. Which HMD are you using?

**Comment by ddutchie** [comment]
Tried last night with oculus. Will try today with vive. 

I'll try capture a video/gif.

**Comment by Corjn** [comment]
Hey, I have the same issue, just opened skinner zip with unity 5.6.0f3, set VR supported, Oculus SDK in PlayerSettings, not working.

**Comment by jvthompson** [comment]
I also am having a similar issue.  As soon as I add Oculus to the list of VR SDKs, I lose all of the Skinner effects, with no errors.

**Comment by Corjn** [comment]
I made some more tests, it's not working with lastest beta of unity 2017 no errors displayed in the console as said in another post here. But it's working with original skinner unity version, that is to say unity 5.4.3f1.
Hope it can help in any way

**Comment by dash-x** [comment]
Hey @keijiro, thanks for this library. Any ideas on the source of the bug for VR? Happy to help resolve it if you've been able to identify some problem areas. Here is an [example project ](https://drive.google.com/file/d/0B-C6hDz5iy5rQnVLc3lBVWdVdGM/view?usp=sharing)in Unity 5.6.2f1 with SteamVR 1.2.2 for reference.

**Comment by Jdakotapowell** [comment]
Ditto - not working in Unity 2017. Will give it a shot in 5.4.3.

**Comment by keijiro** [comment]
I found an issue in Unity's side, and added a workaround for it. Please see #17 for further details.

You can download the new package from here: https://github.com/keijiro/Skinner/releases

To set references to the newly added shaders, SkinnerSource.cs has to be re-added to game objects (remove SkinnerSource components from game objects in your project, then re-add them).

I'm closing this issue now. Please feel free to reopen if you find further problems.
