### ISSUE TITLE
Not running in Unity 5.6 with SteamVR

### ISSUE THREAD

**Issue by mikerz** [keijiro/Skinner#15]
When I run the Test scene with Virtual Reality supported and SteamVR launched, I get absolutely nothing rendering from the SkinnerRenderers (not even the Debug one). It seems that there's some kind of basic incompatibility with your project and SteamVR.

There's no crashing, no error -- just absolutely nothing renders.

**Comment by masterchop** [comment]
This was reported already in issue 14. Please follow that thread. :+1:

**Comment by keijiro** [comment]
I found an issue in Unity's side, and added a workaround for it. Please see #17 for further details.

You can download the new package from here: https://github.com/keijiro/Skinner/releases

To set references to the newly added shaders, SkinnerSource.cs has to be re-added to game objects (remove SkinnerSource components from game objects in your project, then re-add them).

I'm closing this issue now. Please feel free to reopen if you find further problems.
