### ISSUE TITLE
Not working in Unity 2017 or 5.6 w/ VR enabled

### ISSUE THREAD

**Issue by Jdakotapowell** [keijiro/Skinner#17]
Can't get the skinner renderers - Glitch, Particle or Trail - to work in 2017 or 5.6 with VR enabled in player settings. 

When VR is *not* enabled, these renderers work fine in 2017.

Skinner also works in 5.5 and 5.4.3 with VR enabled.

**Comment by laquerida** [comment]
Hi @keijiro, any update on this bug? Would love to use this in a project in 2017.

**Comment by keijiro** [comment]
Actually I have no VR device and no way to test it.

**Comment by keijiro** [comment]
I found an issue on Unity's side. It seems that MRT with Camera.SetTargetBuffers doesn't work in VR

I've already reported it. The issue number is 942235. It will be visible on the issue tracker shortly.

**Comment by keijiro** [comment]
I added a workaround for the VR issue. There is a little performance penalty but there is no other way to avoid it.

You can download the new package from here: https://github.com/keijiro/Skinner/releases

To set references to the newly added shaders, SkinnerSource.cs has to be re-added to game objects. In other words, you have to remove SkinnerSource components from game objects in your project, then re-add them.

I'm closing this issue now. Please feel free to reopen if you meet further problems.

**Comment by dash-x** [comment]
Thanks @keijiro!
