### ISSUE TITLE
Effect jumping between Skinner sources

### ISSUE THREAD

**Issue by dash-x** [keijiro/Skinner#18]
Hey @keijiro, hoping you can shed some light on this issue. The rendered effect seems to be jumping between Skinner sources. Here's a simple project that demonstrates the issue:
[SkinnerBugDemo.zip](https://github.com/keijiro/Skinner/files/1247514/SkinnerBugDemo.zip)

![skinnerbug](https://user-images.githubusercontent.com/30442835/29646121-5d969da8-8836-11e7-8b2b-50118209b2a2.PNG)

**Comment by keijiro** [comment]
Thanks for reporting the issue.

I found there is a regression issue in Unity 2017.1.0. Fortunately I found a simple workaround for the problem. Please try the latest version.

https://github.com/keijiro/Skinner/releases

**Comment by dash-x** [comment]
Thanks @keijiro! Tested and working.
