### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by Swoboderz** [keijiro/Skinner#19]
are you working on any shaders that can take a singular point to draw a trail? since trails from the LineRenderer are probably one of the most common things to have in a Unity Game. (this way you can have Trails on any object. and not just things that are skinned)

**Comment by keijiro** [comment]
I think you can make such effects by using the particle system component (Shuriken).

I'm closing this issue now because this is not relevant to Skinner. Please feel free to reopen for further questions.
