### ISSUE TITLE
Cloth component support

### ISSUE THREAD

**Issue by keijiro** [keijiro/Skinner#2]
Although I'm not sure if it's possible, I note it for future reference.

**Comment by Swoboderz** [comment]
anything with vertices should be compatible shouldn't it?

**Comment by keijiro** [comment]
No. The main focus of Skinner is to feed animated vertex stream from CPU to GPU without excessive load. If it's not animated by CPU, it's pretty trivial so that Skinner is not needed.

**Comment by keijiro** [comment]
This project has been already outdated, so there won't be new features. This should be revisited in Smrvfx: https://github.com/keijiro/Smrvfx
