### ISSUE TITLE
Glitchy Shaders when instancing at run-time

### ISSUE THREAD

**Issue by Swoboderz** [keijiro/Skinner#20]
if you create a prefab that holds your trail object and the actual object itself into aa container. then spawn those two containers it seems as though the shader is running both Synchronously as I see it jump back and forth between the moving objects. https://youtu.be/Lvn_YEMjVCo

**Comment by keijiro** [comment]
I think you're trying to make a trail effect with a non-skinned mesh object. If so, I'd recommend using the standard effect components (like ParticleSystem or LineRenderer) instead, because Skinner is much slower and less memory-efficient than these components.

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
