### ISSUE TITLE
Accessing vertices positions from specific body regions?

### ISSUE THREAD

**Issue by gbernal** [keijiro/Skinner#21]
Hi @ keijiro

I was wondering how could I access the skinned mesh vertices using your project. 
I would like to know how can I access a list of vertices so then I can select random vertices from that list. Then I would like to grow a plant or flowers at random locations.

Is this possible with your setup or would it be overkill?

Thank you for your time and for sharing all your beautiful work?
Guillermo

**Comment by keijiro** [comment]
This project has been outdated. I'd recommend using VFX Graph instead. This kind of customization is easier on it compared to Skinner. See this example for details: https://github.com/keijiro/Smrvfx
