### ISSUE TITLE
iPhoneX test

### ISSUE THREAD

**Issue by bigssu** [keijiro/Skinner#22]
I did build test on iPhoneX but no matter how I change the parameters it only show trail on it's hand and it even stop emitting middle of play.
do you know what happen? or where to go fix it?
![img-0145](https://user-images.githubusercontent.com/10752265/42238511-f03a8752-7eb5-11e8-97ec-a82f25aa768c.jpg)

**Comment by bigssu** [comment]
[trail.zip](https://github.com/keijiro/Skinner/files/2162236/trail.zip)
here is the video that I made

**Comment by keijiro** [comment]
This project has been outdated. I'd recommend use VFX Graph instead. See this example for details: https://github.com/keijiro/Smrvfx
