### ISSUE TITLE
Compatibility with HD Render Pipeline?

### ISSUE THREAD

**Issue by SergioFances** [keijiro/Skinner#23]
Seem that the shaders are not working in the new HD Render Pipeline. Is there any way of making it works?

**Comment by keijiro** [comment]
There is no easy way to convert it to HDRP. It requires a fair amount of time. Unfortunately, my capacity is quite limited. Please don't expect that it'll be converted in the near future.

**Comment by keijiro** [comment]
On HDRP, it's strongly recommended to use VFX Graph instead. See this example for details: https://github.com/keijiro/Smrvfx

**Comment by keijiro** [comment]
I'm closing this issue now. Please feel free to reopen for further questions.
