### ISSUE TITLE
Could you upload a test scene?

### ISSUE THREAD

**Issue by calport** [keijiro/Skinner#24]
This package isn't working in my project, and I'm not sure if it has to do with how Unity changed their shader pipeline, because I'm not able to get the render to show up at all. 

Could you upload a test scene so I could compare how it's working to my issues?

Thanks,
Caroline

**Comment by keijiro** [comment]
I pushed [a small fix](https://github.com/keijiro/Skinner/commit/4f1b8656985d89c92f31d20e93ca1b1446c4640e), so now the test scene works correctly on Unity 2019.3.
