### ISSUE TITLE
Only debug working in 2019.2. Looking for workarounds, can I connect this to Shader Graph?

### ISSUE THREAD

**Issue by BrennonTWilliams** [keijiro/Skinner#26]
I was happy to see that at least SkinnerDebug.cs is working in 2019.2, probably because its the only effect script that runs on the CPU?

Can this data be fed into Shader Graph?

How could I get some kind of effect working using only SkinnerDebug, since it sounds like this will not be updated any time soon?

**Comment by keijiro** [comment]
I haven't maintained this project for a long time, so I'm not sure what's happening in it. I strongly recommend trying Visual Effect Graph instead of Skinner in case of using recent versions of Unity. https://github.com/keijiro/Smrvfx

**Comment by keijiro** [comment]
I confirmed that it still works correctly on Unity 2019.3. I pushed [a small fix](https://github.com/keijiro/Skinner/commit/4f1b8656985d89c92f31d20e93ca1b1446c4640e) for the test scene, so now you can test the basic features with it.

**Comment by keijiro** [comment]
I'm closing this issue now as it doesn't reproduce on my side. Please feel free to reopen if it still reproduces.
