### ISSUE TITLE
HDRP conversion

### ISSUE THREAD

**Issue by lajaraster** [keijiro/Skinner#28]
Hi,
First, this is an amazing effect, @keijiro . I've tried to upgrade the project to HDRP but the materials doesn't convert properly. Is there something I can make to fix it?
Thx

**Comment by keijiro** [comment]
The short answer is no. You can't just fix it -- you have to reimplement the whole things. Please understand that Skinner doesn't any SRP (HDRP/URP).

I'd recommend using Smrvfx instead. You can create similar effects, and it's far easier to extend and maintain.

https://github.com/keijiro/Smrvfx

**Comment by lajaraster** [comment]
Oh, nice! Thank you very much
