### ISSUE TITLE
Possible to map a mocap suit controller to your avatar? 

### ISSUE THREAD

**Issue by Lightsteed** [keijiro/Skinner#3]
I woukd like to try implement this project for a live performance using the perception neuron mocap suit, do you know if that would be possible with the project in its current state? I managed to get it to a. Point where it somewhat works, but the mapping of the particles and effects in respect to the animation is not correct. 
P. S. I love your work and have been playing around with your projects for a while, modifying them and using them in VR on the HTC vive -  so so beautiful!

**Comment by keijiro** [comment]
It's still under development :wink:

Skinner needs some special steps to set up a model. I'll write a manual for it, but at the moment it might be completely mysterious to you. Please stay tuned!

If it goes well, it'll be finished in the end of the year.

**Comment by Lightsteed** [comment]
Awesome thanks for replying - I actually have worked it out now though, i'm using a re targetting script i found that someone made for PN. I still need to use your model for the effects to work properly as far as i can tell, but it looks great and maps perfectly to the suit in realtime so i'm very happy for now. will send video if we end up using it in a live performance! thanks
