### ISSUE TITLE
Custom Particle Systems

### ISSUE THREAD

**Issue by baughbj** [keijiro/Skinner#30]
Hello,

Is it possible to use a custom particle system for the skinner particle template? If so, how would I do it?I would like to create an effect with a character made out of water.

**Comment by keijiro** [comment]
Yes. I'd recommend modifying existing shaders rather than writing the shader from scratch.

By the way, I haven't used this project for years. Now I'm using Smrvfx instead.

https://github.com/keijiro/Smrvfx

It's far easier to extend. I'd recommend using it instead of Skinner.
