### ISSUE TITLE
Changing simulation space to world

### ISSUE THREAD

**Issue by mutp** [keijiro/Skinner#31]
We are trying to achieve glitch effect with gpu particles system in built-in and you have already made that effect but the issue it has that system is always in local simulation space.
Is there a way to change the simulation space to world?

![glitch sim space](https://user-images.githubusercontent.com/8210008/88921413-1d79d700-d28c-11ea-8025-000d9b4c135d.gif)

**Comment by keijiro** [comment]
Skinner doesn't support world space simulation.

I'd strongly recommend using Smrvfx instead. It's far easier to customize.

https://github.com/keijiro/Smrvfx

**Comment by mutp** [comment]
I would have loved to use it, but, unfortunately, we need to stick to built-in pipeline so the VFX graph isn't an option for us.
I'm trying to get GPU particles (with SkinnedMeshRenderer) working in built-in pipeline but haven't found anything straightforward yet. This came closest, but I needed world space simulation.
