### ISSUE TITLE
URP support

### ISSUE THREAD

**Issue by fanstudiouk** [keijiro/Skinner#32]
Hey there, 

Congrats for your work! I love this shader, but unfortunatelly it's not supported with the URP.
Do you have any plans to port it soon to Shader Graph? 

Thanks!

**Comment by keijiro** [comment]
Please check https://github.com/keijiro/Smrvfx

**Comment by fanstudiouk** [comment]
Wow, impressive! Thanks a lot for sharing this! It would be nice to upload it to Unity asset store so we can buy it and support your work :)
