### ISSUE TITLE
Constant updated mesh created programatically (ER)

### ISSUE THREAD

**Issue by masterchop** [keijiro/Skinner#6]
Hello kei,

   Awesome work as usual 👍 , i wonder if i can apply this to a mesh created programatically from a pointcloud that its updated and reacreated on every frame.

The plug in requires to point an already creatd mesh but this is created at runtime.

**Comment by keijiro** [comment]
You mean that you're trying to use a pointcloud that is not a skinned mesh? That sounds like a cool idea, but the main scope of Skinner is adding effects to skinned mesh objects (as the name implies). I think it should be implemented as another package rather than extending Skinner.

**Comment by masterchop** [comment]
I think i can create a skinned mesh from the point cloud, the point was that it can only be applied to pre-creaded skinned meshes, not created at run time.

I found a workaround to place it at the same location and seemed legit XD

**Comment by keijiro** [comment]
I got it. Actually you can create a SkinnerModel at run time if you remove the following ifdef line:

https://github.com/keijiro/Skinner/blob/master/Assets/Skinner/SkinnerModel.cs#L34

Yeah, that workaround would work well. The SkinnerMode.Initialize function above is memory/CPU intensive and not recommended to use at run time.

**Comment by masterchop** [comment]
i couldnt resist and found out the bad way, thanks for your inputs.
