### ISSUE TITLE
Convert Mesh shows IndexOutOfRangeException error

### ISSUE THREAD

**Issue by yanjingzhaisun** [keijiro/Skinner#8]
Converting mesh failed at a voxel mesh object.
error:

```
IndexOutOfRangeException: Array index is out of range.
Skinner.SkinnerModel.Initialize (UnityEngine.Mesh source) (at Assets/Plugins/Skinner/SkinnerModel.cs:57)
Skinner.SkinnerModelEditor.ConvertAssets () (at Assets/Plugins/Skinner/Editor/SkinnerModelEditor.cs:62)
```

target mesh:
[TanukiAdult_mesh_skinner.asset.zip](https://github.com/keijiro/Skinner/files/727065/TanukiAdult_mesh_skinner.asset.zip)

**Comment by keijiro** [comment]
It seems that this model doesn't have any tangents -- Skinner needs tangents for each vertex.

You can avoid this limitation by changing the following line:

https://github.com/keijiro/Skinner/blob/master/Assets/Skinner/SkinnerModel.cs#L57

to this:

```
   outTangents.Add(new Vector4(0, 0, 1, 1));
```

This change may cause some minor issues, but I think it works anyway.

**Comment by keijiro** [comment]
I'm closing this issue. Please feel free to reopen if you find further issues.
