### ISSUE TITLE
Running on iPhone 5s

### ISSUE THREAD

**Issue by nibab** [keijiro/Skinner#9]
I am getting the following issue on building for iPhone 5s:

`This set of render targets requires 24 bytes of pixel storage. This device supports 16 bytes.`

It does work on iPhone 6, so I am a bit puzzled. Could it be that the GPU is too weak on the 5s?

**Comment by keijiro** [comment]
Which iOS version is the device running? According to the capability list, iPhone 5s is compatible with it only when running on iOS 10.

https://developer.apple.com/metal/capabilities/

**Comment by nibab** [comment]
@keijiro iOS 10.1 😕

**Comment by keijiro** [comment]
Sure. Thanks for clarification. I suspect that it's a bug on Unity's side. I'll look into it later.

**Comment by keijiro** [comment]
Sorry for not updating this issue for years, but I think it should be closed now because iPhone 5S has been already outdated. I think I shouldn't invest my time on this specific problem.
